# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-02 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Children_clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Diapers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Milk_powder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pregnant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('smallimg', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaccount', models.CharField(max_length=60)),
                ('uname', models.CharField(max_length=60)),
                ('upwd', models.CharField(max_length=256)),
                ('utel', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
