# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-07 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_select', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smallimg', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=100)),
                ('packet', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=50)),
                ('rated', models.CharField(max_length=40)),
                ('each', models.CharField(max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('purchase', models.IntegerField()),
                ('right', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uaccount', models.CharField(max_length=60)),
                ('uname', models.CharField(max_length=60)),
                ('upwd', models.CharField(max_length=256)),
                ('utel', models.CharField(max_length=20)),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mall.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mall.User'),
        ),
    ]
