# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-31 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mall', '0002_auto_20181031_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=60),
        ),
    ]
