# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-10 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mall', '0005_auto_20181110_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_select',
            field=models.BooleanField(default=True),
        ),
    ]
