# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-11 06:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mall', '0007_order_ordergoods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='identifier',
            new_name='orderno',
        ),
    ]
